# netlify.toml

# Caching settings
[[headers]]
  # Cache settings for JS files
  for = "*.js"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache settings for CSS files
  for = "*.css"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache settings for image files (jpg, jpeg, png, gif, svg)
  for = "*.jpg"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
  for = "*.jpeg"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
  for = "*.png"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
  for = "*.gif"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
  for = "*.svg"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
